# -*- coding: utf-8 -*-
"""drop duplicate index(cluster).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V2ItV5X6oQqBUgGXBFCFoceWE_Ozx1V8
"""

import pandas as pd

# making data frame from csv file
data = pd.read_csv("output3.csv")

data

data.drop_duplicates(subset='level_0',
                     keep='first', inplace= True)

# displaying data
data

data.drop_duplicates(subset='level_1',
                     keep='first', inplace= True)

# displaying data
data

import pandas as pd
pd.DataFrame.from_records(data)

from google.colab import files
data.to_csv('output3f.csv', encoding = 'utf-8-sig')
files.download('output3f.csv')